/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AvisosRouteImport } from './routes/avisos'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PlacasRouteImport } from './routes/placas'
import { Route as PuntosRouteImport } from './routes/puntos'
import { Route as TurnosRouteImport } from './routes/turnos'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AvisosRoute = AvisosRouteImport.update({
  id: '/avisos',
  path: '/avisos',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PlacasRoute = PlacasRouteImport.update({
  id: '/placas',
  path: '/placas',
  getParentRoute: () => rootRouteImport,
} as any)
const PuntosRoute = PuntosRouteImport.update({
  id: '/puntos',
  path: '/puntos',
  getParentRoute: () => rootRouteImport,
} as any)
const TurnosRoute = TurnosRouteImport.update({
  id: '/turnos',
  path: '/turnos',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/avisos': typeof AvisosRoute
  '/login': typeof LoginRoute
  '/placas': typeof PlacasRoute
  '/puntos': typeof PuntosRoute
  '/turnos': typeof TurnosRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/avisos': typeof AvisosRoute
  '/login': typeof LoginRoute
  '/placas': typeof PlacasRoute
  '/puntos': typeof PuntosRoute
  '/turnos': typeof TurnosRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/avisos': typeof AvisosRoute
  '/login': typeof LoginRoute
  '/placas': typeof PlacasRoute
  '/puntos': typeof PuntosRoute
  '/turnos': typeof TurnosRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/avisos'
    | '/login'
    | '/placas'
    | '/puntos'
    | '/turnos'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/avisos'
    | '/login'
    | '/placas'
    | '/puntos'
    | '/turnos'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/avisos'
    | '/login'
    | '/placas'
    | '/puntos'
    | '/turnos'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AvisosRoute: typeof AvisosRoute
  LoginRoute: typeof LoginRoute
  PlacasRoute: typeof PlacasRoute
  PuntosRoute: typeof PuntosRoute
  TurnosRoute: typeof TurnosRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avisos': {
      id: '/avisos'
      path: '/avisos'
      fullPath: '/avisos'
      preLoaderRoute: typeof AvisosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/placas': {
      id: '/placas'
      path: '/placas'
      fullPath: '/placas'
      preLoaderRoute: typeof PlacasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/puntos': {
      id: '/puntos'
      path: '/puntos'
      fullPath: '/puntos'
      preLoaderRoute: typeof PuntosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/turnos': {
      id: '/turnos'
      path: '/turnos'
      fullPath: '/turnos'
      preLoaderRoute: typeof TurnosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AvisosRoute: AvisosRoute,
  LoginRoute: LoginRoute,
  PlacasRoute: PlacasRoute,
  PuntosRoute: PuntosRoute,
  TurnosRoute: TurnosRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
